{% set name = "sortedcontainers" %}
{% set version = "2.0.5" %}
{% set sha256 = "b74f2756fb5e23512572cc76f0fe0832fd86310f77dfee54335a35fb33f6b950" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python


test:
  imports:
    - sortedcontainers

about:
  home: http://www.grantjenks.com/docs/sortedcontainers/
  license: Apache 2.0
  summary: 'Python Sorted Container Types: SortedList, SortedDict, and SortedSet'
  description: |
    SortedContainers is a sorted collections library, written in pure-Python
    and fast as C-extensions.
  doc_url: http://www.grantjenks.com/docs/sortedcontainers/
  dev_url: https://github.com/grantjenks/sorted_containers/
  doc_source_url: https://github.com/grantjenks/sorted_containers/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - grantjenks
    - msarahan
    - richafrank
    - nehaljwani
