travis:
  secure:
    BINSTAR_TOKEN: vXW791hW6mp5nQ3H2SsZmMdgENJgRsmmU1zxOPkH6cyqXR/chlIfVUEua/dRV+BtaV3AlWceqYcl0ev/IkyW97pcePXdCU4uRlKSUNWljl+9GKL/jgOGCYsd1roRul+fd0xtEFCW+pg/q7Lh83yLXVMOPRemrk1dWS9wv/svT+0ftwGZaIBrRv43j9OAyMaY9lBkBkz6zHdYAarE1NRoAdNmJ3n1IsMXECCx6ql/CJqoNh4I4oX3thjEq30yRRD1Z5zsGkVLC/7z2TElaBounw1AoHQy4T2T3lLWLhTK/YUbsdEA7g+aJKU59s6c3xJetMd+rUZY3nfUUGr7wMk3Z+pff/RghZ21esna4x2frxDdPbOqS1Gu6qig3R1108LPmOpfK/B/yvZUJ6cBxEYg4lxe+rLMKs+hJhtmn7jLeHiTqx1sGI3DJptRpwD1ek/2N1X0yVN8720rLdbS0raV67I5XuaNSgytPPEjMTtHd2flrzRhZMFG/X6ep2jhfdK8q8GbmUalRj5EjQW5gJu742dc9hujg2WCBwdsezSf6sr7y74JjzY4LtouRnliD4Es6ax7ii4Bt7W0Ev9T7/vjRinOQB/HSm1p1kXTjw0pJRUe8JE75FeFtdGAZrbaF+73zoiC8KtPSgWfYSxL414QwCAOTD7hu9Nl3ZdGvZSSumI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
