travis:
  secure:
    BINSTAR_TOKEN: Vs8rN5g99f/P6R6XIbLE09vio7abIctmdjnrej0/NpJBuzM+fbSRYAIz5R0Nzioat2hU1ilpQMu2OJHh++PLovrYr9L4qftTVDTkqeetKHjSFsX5F2x1sE5zopB9HMuJxwRM9gjRvMN/8ITbwg+yzoFniS1BvsGd0629gvEKI/qWilUQVgBJy7tWYZiU+ql30aNxb6bbSdy+YM78jQu7FKSLsryFrIWCYiCabkiKqop6qZu2dKPVVIBFJtYKjSia+JwCLg+WdZT0RdE9MfPvF8l4ZRHIgoQR+AG3ZFtn+oXfMsBc2LKHP2zX6fSDm2k/jb5+Yf5yZG1DETRfWySC/ddH/a/bMeo3vsE3Ss4fJlDeZMkanFejYO+3IZ6pVbpH+srqeWKj4HcYesb8BnhMiDoksYliuVuEE9uDeB+GU5YMcigNxGzlY9fuZr3slUVduKIpccOL5eZ5abVy0CbP4tGysodLiVJ9DQcxnXN5Jh1zSapvJuJFQCnN97eGlIIbt9hFyRHVvRIcbBInfdSng/XcOW6hqe6TNICauN+HmuLrDx1rdWRFDtngGMzki+AhwW8YKn8UvsZ9YnIlicd2fctHAWjm2euFil/FEPjKxqV0cDNQv/Tzb7kKpk9JY+iV3tRutU8wI7VOMhtSCaA97XKAN8P5+5pTOib8VEtnRNI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
