travis:
  secure:
    BINSTAR_TOKEN: q9UVuJTaz0e+anrhCI/2xFNuY5xpALPibxXGp9kr5o/9IwipvqrQFtJil+6w7TPAlR88AWSNv7XDqBNRnjy3ewaFtz/GamsdYp0+HXGXBcCQ+xggn4v5LAioj6sy7EGTrO6PpffBQJ9DHwHpGrHrhS/6wQ93Tf8EkWbN0c1JAEJiZYH8evd7a+f/b7/9WnjE1QmvTwXK8v1oqv3sYIWjvQfDks/RAx1Ye41MYaWsURMLtyL37IBDsoxYatxv2HLnt8WEvH6s5Iz4ClXArMOd2uDu69C1qYKvksBHh7gKR0CdNMAjxoe3/OVWLIwN6goNKGJORCDm1z9HT9jTb3w90CKtTMx2hQUBsZ2qKJNH44BvW7fC+jq161XZI/wUt57iAaAI9QMHVRz7NvGFeXkUe9b3Rm3UAd1Bj42qlq6k1womHOQEz95gyjigNHKNEsmevSIJbsXX+kWokjT8dmUtJrCMoKf1zwuUv8SHNRCkJA7xdfWYI8BUTjXL77S4JIWgS8gROWRxifMDwlamClr0gDGM2E4ZBjKO/abEQNnO8XV7UU/Msob5aL+h3hlpxY/J33shC/vU2WKvxfWWY4VCS+wkcNaZyisyd1kXHYA38ZV5kaqfRe97ahENm98b01e020OYKNkDRqg72SmtecDRFJC5yRvDdSY0CmR06S8gw5A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
